### ISSUE TITLE
DLL loading issue

### ISSUE THREAD

**Issue by alejzeis** [DerelictOrg/DerelictVorbis#2] opened 2016-08-20 00:27 UTC
I am using Windows 10 (64 bit). My application is compiled for 32 bit, and all the DLLs are 32 bit aswell.

The Loader fails to load the DLLs saying "The specified Module could not be found", when it does exist in the right place. Research shows that this is an issue with DLL dependencies, but I built the DLLs (libogg, libvorbis, and libvorbisfile) manually using Visual Studio 2015 community (with the VS2010 project provided in the source distribution).

Should I close this and open an issue at DerelictUtil as the problem is with the loader?

More information [here.](http://stackoverflow.com/questions/39048413/issue-with-loading-a-dll)

**Comment by mdparker** [comment] 2017-02-27 05:47
Wow, so sorry. I somehow missed both this and your DerelictOgg issue. Did you ever solve it? I'm going through and updating all of the packages, so if there is an unsolved issue here I'd like to dig into it. Sorry again.

**Comment by alejzeis** [comment] 2017-02-28 13:30
I ended up just using libsndfile, using the unofficial DerelictSndFile
binding. This issue is still unsolved.

**Comment by mdparker** [comment] 2017-03-29 11:40
I was unable to reproduce this. I compiled both libogg and libvorbis with VS 2015. I did have an error with a missing function in libvorbis, but once I fixed that it all loaded fine. Since you've moved on, no one else has reported it, and I can't reproduce it, I'm closing this one.

**Closed as completed by mdparker** 2017-03-29 11:40 UTC

**Comment by alejzeis** [comment] 2017-03-29 15:09
Alright, if I ever come across the problem again I'll post again.
